#!/usr/bin/env python3
"""Practical self-test for shortcuts-builder.

Checks:
1. local validator works on a minimal generated draft
2. signer works on a known-good draft already validated in Minis workflow
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path("/var/minis/skills/shortcuts-builder")
OUT = Path("/var/minis/attachments/shortcut")
DRAFTS = OUT / "drafts"
TEST_XML = DRAFTS / "Selftest Hello.xml"

XML = """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"> 
<plist version=\"1.0\"> 
<dict>
    <key>WFWorkflowActions</key>
    <array>
        <dict>
            <key>WFWorkflowActionIdentifier</key>
            <string>is.workflow.actions.comment</string>
            <key>WFWorkflowActionParameters</key>
            <dict>
                <key>WFCommentActionText</key>
                <string>Self-test shortcut.</string>
            </dict>
        </dict>
        <dict>
            <key>WFWorkflowActionIdentifier</key>
            <string>is.workflow.actions.comment</string>
            <key>WFWorkflowActionParameters</key>
            <dict>
                <key>WFCommentActionText</key>
                <string>Shortcuts generated by Shortcuts Playground. May contain mistakes. Always check the shortcut's actions first.</string>
            </dict>
        </dict>
        <dict>
            <key>WFWorkflowActionIdentifier</key>
            <string>is.workflow.actions.gettext</string>
            <key>WFWorkflowActionParameters</key>
            <dict>
                <key>UUID</key>
                <string>F3CB8E1B-2A79-46AB-BE6A-6E2D5EB80411</string>
                <key>WFTextActionText</key>
                <string>Hello from Minis</string>
            </dict>
        </dict>
        <dict>
            <key>WFWorkflowActionIdentifier</key>
            <string>is.workflow.actions.showresult</string>
            <key>WFWorkflowActionParameters</key>
            <dict>
                <key>Text</key>
                <dict>
                    <key>Value</key>
                    <dict>
                        <key>attachmentsByRange</key>
                        <dict>
                            <key>{0, 1}</key>
                            <dict>
                                <key>OutputName</key>
                                <string>Text</string>
                                <key>OutputUUID</key>
                                <string>F3CB8E1B-2A79-46AB-BE6A-6E2D5EB80411</string>
                                <key>Type</key>
                                <string>ActionOutput</string>
                            </dict>
                        </dict>
                        <key>string</key>
                        <string>￼</string>
                    </dict>
                    <key>WFSerializationType</key>
                    <string>WFTextTokenString</string>
                </dict>
            </dict>
        </dict>
    </array>
    <key>WFWorkflowClientVersion</key>
    <string>2700.0.4</string>
    <key>WFWorkflowHasOutputFallback</key>
    <false/>
    <key>WFWorkflowIcon</key>
    <dict>
        <key>WFWorkflowIconGlyphNumber</key>
        <integer>61440</integer>
        <key>WFWorkflowIconStartColor</key>
        <integer>431817727</integer>
    </dict>
    <key>WFWorkflowImportQuestions</key>
    <array/>
    <key>WFWorkflowMinimumClientVersion</key>
    <integer>900</integer>
    <key>WFWorkflowMinimumClientVersionString</key>
    <string>900</string>
    <key>WFWorkflowName</key>
    <string>Selftest Hello</string>
    <key>WFWorkflowTypes</key>
    <array/>
</dict>
</plist>
"""


def run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, text=True, capture_output=True)


def fail(stage: str, stdout: str, stderr: str) -> int:
    print(json.dumps({"ok": False, "stage": stage, "stdout": stdout, "stderr": stderr}, ensure_ascii=False, indent=2))
    return 1


def main() -> int:
    DRAFTS.mkdir(parents=True, exist_ok=True)
    TEST_XML.write_text(XML, encoding="utf-8")

    validate = run(sys.executable, str(ROOT / "scripts/validate_shortcut.py"), str(TEST_XML))
    if validate.returncode != 0:
        return fail("validate_minimal_draft", validate.stdout, validate.stderr)

    cfg = run(sys.executable, str(ROOT / "scripts/sign_shortcut.py"), "--show-config")
    if "--sign" not in sys.argv:
        print(json.dumps({"ok": True, "signed": False, "note": "validation only; pass --sign to also test the configured signing backend",
                          "signing_config": json.loads(cfg.stdout or "{}")}, ensure_ascii=False))
        return 0

    sign = run(sys.executable, str(ROOT / "scripts/sign_shortcut.py"), str(TEST_XML), "--name", "Selftest Hello")
    if sign.returncode != 0:
        return fail("sign_minimal_draft", sign.stdout, sign.stderr)

    print(sign.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
